import { db } from '@/db';
import { menuItems } from '@/db/schema';

async function main() {
    const sampleMenuItems = [
        {
            categoryId: 1,
            nameEn: 'Turkish Coffee',
            nameKu: 'Qahweya Tirkî',
            descriptionEn: 'Traditional Turkish coffee served in authentic style with a rich, bold flavor',
            descriptionKu: 'Qahweya Tirkî ya kevneşopî bi tama xurt û dewlemend',
            price: 3.50,
            imageUrl: '/images/menu/turkish-coffee.jpg',
            isAvailable: true,
            preparationTime: 5,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 1,
            nameEn: 'Cappuccino',
            nameKu: 'Kapuçîno',
            descriptionEn: 'Classic Italian cappuccino with rich espresso and creamy steamed milk',
            descriptionKu: 'Kapuçînoyek Îtalî bi espreso û şîrê krêmî',
            price: 4.00,
            imageUrl: '/images/menu/cappuccino.jpg',
            isAvailable: true,
            preparationTime: 3,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 1,
            nameEn: 'Fresh Orange Juice',
            nameKu: 'Aba Pirteqalî Taze',
            descriptionEn: 'Freshly squeezed orange juice packed with vitamins and natural sweetness',
            descriptionKu: 'Aba pirteqalî ya taze bi vîtamîn û şîrîniya xwezayî',
            price: 3.00,
            imageUrl: '/images/menu/fresh-orange-juice.jpg',
            isAvailable: true,
            preparationTime: 2,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 1,
            nameEn: 'Kurdish Tea',
            nameKu: 'Çayî Kurdî',
            descriptionEn: 'Aromatic Kurdish tea brewed to perfection, served hot with traditional hospitality',
            descriptionKu: 'Çayê Kurdî bi bênbêjî û germahî ya kevneşopî',
            price: 2.00,
            imageUrl: '/images/menu/kurdish-tea.jpg',
            isAvailable: true,
            preparationTime: 2,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 2,
            nameEn: 'Kebab',
            nameKu: 'Kebab',
            descriptionEn: 'Grilled meat skewers',
            descriptionKu: 'Goşt û birinc',
            price: 12.00,
            imageUrl: '/images/menu/kebab.jpg',
            isAvailable: true,
            preparationTime: 20,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 2,
            nameEn: 'Dolma',
            nameKu: 'Dolme',
            descriptionEn: 'Stuffed grape leaves',
            descriptionKu: 'Gelapêçî tijî',
            price: 10.00,
            imageUrl: '/images/menu/dolma.jpg',
            isAvailable: true,
            preparationTime: 30,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 2,
            nameEn: 'Biryani',
            nameKu: 'Biryanî',
            descriptionEn: 'Spiced rice with meat',
            descriptionKu: 'Birinc bi goşt û baharat',
            price: 11.00,
            imageUrl: '/images/menu/biryani.jpg',
            isAvailable: true,
            preparationTime: 25,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 2,
            nameEn: 'Grilled Chicken',
            nameKu: 'Mirîşka Biryankirin',
            descriptionEn: 'Tender grilled chicken marinated with aromatic spices and herbs',
            descriptionKu: 'Mirîşka nerm a biryankirî bi baharat û riwekên xweşbîhn',
            price: 13.00,
            imageUrl: '/images/menu/grilled-chicken.jpg',
            isAvailable: true,
            preparationTime: 25,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 3,
            nameEn: 'Baklava',
            nameKu: 'Beqlawe',
            descriptionEn: 'Layered pastry with nuts',
            descriptionKu: 'Pastrîya şîrîn bi gûz',
            price: 5.00,
            imageUrl: '/images/menu/baklava.jpg',
            isAvailable: true,
            preparationTime: 5,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 3,
            nameEn: 'Kunafa',
            nameKu: 'Kinafe',
            descriptionEn: 'Sweet cheese pastry',
            descriptionKu: 'Pastrîya şîrîn bi penîr',
            price: 6.00,
            imageUrl: '/images/menu/kunafa.jpg',
            isAvailable: true,
            preparationTime: 10,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 3,
            nameEn: 'Chocolate Cake',
            nameKu: 'Cakî Çokolate',
            descriptionEn: 'Rich and moist chocolate cake with smooth chocolate frosting',
            descriptionKu: 'Cakê çokolateyê dewlemend û nerm bi glaseyê çokolateyê',
            price: 5.50,
            imageUrl: '/images/menu/chocolate-cake.jpg',
            isAvailable: true,
            preparationTime: 5,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 4,
            nameEn: 'Hummus',
            nameKu: 'Humus',
            descriptionEn: 'Chickpea dip',
            descriptionKu: 'Dîpê nîskê',
            price: 4.50,
            imageUrl: '/images/menu/hummus.jpg',
            isAvailable: true,
            preparationTime: 5,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 4,
            nameEn: 'Tabbouleh',
            nameKu: 'Tebbûle',
            descriptionEn: 'Fresh parsley salad',
            descriptionKu: 'Salateya toxunê taze',
            price: 5.00,
            imageUrl: '/images/menu/tabbouleh.jpg',
            isAvailable: true,
            preparationTime: 10,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 4,
            nameEn: 'Fattoush',
            nameKu: 'Fatûş',
            descriptionEn: 'Mixed salad with crispy bread',
            descriptionKu: 'Salateya çelêmê',
            price: 5.50,
            imageUrl: '/images/menu/fattoush.jpg',
            isAvailable: true,
            preparationTime: 8,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            categoryId: 4,
            nameEn: 'Baba Ghanoush',
            nameKu: 'Baba Ġanûş',
            descriptionEn: 'Smoky eggplant dip',
            descriptionKu: 'Dîpê bacanê',
            price: 4.75,
            imageUrl: '/images/menu/baba-ghanoush.jpg',
            isAvailable: true,
            preparationTime: 7,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(menuItems).values(sampleMenuItems);
    
    console.log('✅ Menu items seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});