import { db } from '@/db';
import { orders, orderItems } from '@/db/schema';

async function main() {
    const now = new Date();
    const twoHoursAgo = new Date(now.getTime() - 2 * 60 * 60 * 1000);
    const threeHoursAgo = new Date(now.getTime() - 3 * 60 * 60 * 1000);
    const thirtyMinutesAgo = new Date(now.getTime() - 30 * 60 * 1000);

    const sampleOrders = [
        {
            tableId: 3,
            garsonId: 3,
            status: 'served',
            totalAmount: 18.50,
            discountAmount: 0,
            finalAmount: 18.50,
            paymentMethod: null,
            notes: null,
            createdAt: new Date(threeHoursAgo.getTime() + 15 * 60 * 1000).toISOString(),
            updatedAt: new Date(thirtyMinutesAgo.getTime() - 5 * 60 * 1000).toISOString(),
            completedAt: null,
        },
        {
            tableId: 7,
            garsonId: 4,
            status: 'served',
            totalAmount: 35.50,
            discountAmount: 2.00,
            finalAmount: 33.50,
            paymentMethod: null,
            notes: 'Customer requested extra napkins',
            createdAt: new Date(twoHoursAgo.getTime() + 45 * 60 * 1000).toISOString(),
            updatedAt: new Date(thirtyMinutesAgo.getTime() - 2 * 60 * 1000).toISOString(),
            completedAt: null,
        },
        {
            tableId: 12,
            garsonId: 3,
            status: 'served',
            totalAmount: 52.25,
            discountAmount: 0,
            finalAmount: 52.25,
            paymentMethod: null,
            notes: null,
            createdAt: new Date(threeHoursAgo.getTime() + 30 * 60 * 1000).toISOString(),
            updatedAt: new Date(thirtyMinutesAgo.getTime()).toISOString(),
            completedAt: null,
        },
        {
            tableId: 5,
            garsonId: 4,
            status: 'served',
            totalAmount: 23.00,
            discountAmount: 1.50,
            finalAmount: 21.50,
            paymentMethod: null,
            notes: 'Birthday celebration table',
            createdAt: new Date(twoHoursAgo.getTime() + 20 * 60 * 1000).toISOString(),
            updatedAt: new Date(thirtyMinutesAgo.getTime() - 8 * 60 * 1000).toISOString(),
            completedAt: null,
        },
        {
            tableId: 9,
            garsonId: 3,
            status: 'served',
            totalAmount: 44.75,
            discountAmount: 0,
            finalAmount: 44.75,
            paymentMethod: null,
            notes: null,
            createdAt: new Date(threeHoursAgo.getTime() + 50 * 60 * 1000).toISOString(),
            updatedAt: new Date(thirtyMinutesAgo.getTime() - 10 * 60 * 1000).toISOString(),
            completedAt: null,
        },
        {
            tableId: 1,
            garsonId: 4,
            status: 'served',
            totalAmount: 16.50,
            discountAmount: 0,
            finalAmount: 16.50,
            paymentMethod: null,
            notes: 'Customer allergic to nuts',
            createdAt: new Date(twoHoursAgo.getTime() + 35 * 60 * 1000).toISOString(),
            updatedAt: new Date(thirtyMinutesAgo.getTime() - 3 * 60 * 1000).toISOString(),
            completedAt: null,
        },
        {
            tableId: 14,
            garsonId: 3,
            status: 'served',
            totalAmount: 58.50,
            discountAmount: 3.50,
            finalAmount: 55.00,
            paymentMethod: null,
            notes: null,
            createdAt: new Date(threeHoursAgo.getTime() + 10 * 60 * 1000).toISOString(),
            updatedAt: new Date(thirtyMinutesAgo.getTime() - 1 * 60 * 1000).toISOString(),
            completedAt: null,
        },
        {
            tableId: 8,
            garsonId: 4,
            status: 'served',
            totalAmount: 27.50,
            discountAmount: 0,
            finalAmount: 27.50,
            paymentMethod: null,
            notes: 'Rush order - customer in hurry',
            createdAt: new Date(twoHoursAgo.getTime() + 55 * 60 * 1000).toISOString(),
            updatedAt: new Date(thirtyMinutesAgo.getTime() - 12 * 60 * 1000).toISOString(),
            completedAt: null,
        },
    ];

    await db.insert(orders).values(sampleOrders);

    const sampleOrderItems = [
        // Order 1 items (tableId: 3, total: 18.50)
        {
            orderId: 1,
            menuItemId: 1,
            quantity: 2,
            unitPrice: 3.50,
            subtotal: 7.00,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 15 * 60 * 1000).toISOString(),
        },
        {
            orderId: 1,
            menuItemId: 9,
            quantity: 1,
            unitPrice: 5.00,
            subtotal: 5.00,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 15 * 60 * 1000).toISOString(),
        },
        {
            orderId: 1,
            menuItemId: 10,
            quantity: 1,
            unitPrice: 6.00,
            subtotal: 6.00,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 15 * 60 * 1000).toISOString(),
        },

        // Order 2 items (tableId: 7, total: 35.50)
        {
            orderId: 2,
            menuItemId: 5,
            quantity: 2,
            unitPrice: 12.00,
            subtotal: 24.00,
            notes: null,
            status: 'served',
            createdAt: new Date(twoHoursAgo.getTime() + 45 * 60 * 1000).toISOString(),
        },
        {
            orderId: 2,
            menuItemId: 2,
            quantity: 2,
            unitPrice: 4.00,
            subtotal: 8.00,
            notes: null,
            status: 'served',
            createdAt: new Date(twoHoursAgo.getTime() + 45 * 60 * 1000).toISOString(),
        },
        {
            orderId: 2,
            menuItemId: 13,
            quantity: 1,
            unitPrice: 5.00,
            subtotal: 5.00,
            notes: null,
            status: 'served',
            createdAt: new Date(twoHoursAgo.getTime() + 45 * 60 * 1000).toISOString(),
        },

        // Order 3 items (tableId: 12, total: 52.25)
        {
            orderId: 3,
            menuItemId: 8,
            quantity: 3,
            unitPrice: 13.00,
            subtotal: 39.00,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 30 * 60 * 1000).toISOString(),
        },
        {
            orderId: 3,
            menuItemId: 12,
            quantity: 2,
            unitPrice: 4.50,
            subtotal: 9.00,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 30 * 60 * 1000).toISOString(),
        },
        {
            orderId: 3,
            menuItemId: 4,
            quantity: 2,
            unitPrice: 2.00,
            subtotal: 4.00,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 30 * 60 * 1000).toISOString(),
        },

        // Order 4 items (tableId: 5, total: 23.00)
        {
            orderId: 4,
            menuItemId: 6,
            quantity: 1,
            unitPrice: 10.00,
            subtotal: 10.00,
            notes: null,
            status: 'served',
            createdAt: new Date(twoHoursAgo.getTime() + 20 * 60 * 1000).toISOString(),
        },
        {
            orderId: 4,
            menuItemId: 14,
            quantity: 2,
            unitPrice: 5.50,
            subtotal: 11.00,
            notes: null,
            status: 'served',
            createdAt: new Date(twoHoursAgo.getTime() + 20 * 60 * 1000).toISOString(),
        },
        {
            orderId: 4,
            menuItemId: 4,
            quantity: 1,
            unitPrice: 2.00,
            subtotal: 2.00,
            notes: null,
            status: 'served',
            createdAt: new Date(twoHoursAgo.getTime() + 20 * 60 * 1000).toISOString(),
        },

        // Order 5 items (tableId: 9, total: 44.75)
        {
            orderId: 5,
            menuItemId: 7,
            quantity: 2,
            unitPrice: 11.00,
            subtotal: 22.00,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 50 * 60 * 1000).toISOString(),
        },
        {
            orderId: 5,
            menuItemId: 15,
            quantity: 3,
            unitPrice: 4.75,
            subtotal: 14.25,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 50 * 60 * 1000).toISOString(),
        },
        {
            orderId: 5,
            menuItemId: 3,
            quantity: 2,
            unitPrice: 3.00,
            subtotal: 6.00,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 50 * 60 * 1000).toISOString(),
        },

        // Order 6 items (tableId: 1, total: 16.50)
        {
            orderId: 6,
            menuItemId: 11,
            quantity: 2,
            unitPrice: 5.50,
            subtotal: 11.00,
            notes: 'No nuts',
            status: 'served',
            createdAt: new Date(twoHoursAgo.getTime() + 35 * 60 * 1000).toISOString(),
        },
        {
            orderId: 6,
            menuItemId: 13,
            quantity: 1,
            unitPrice: 5.00,
            subtotal: 5.00,
            notes: null,
            status: 'served',
            createdAt: new Date(twoHoursAgo.getTime() + 35 * 60 * 1000).toISOString(),
        },

        // Order 7 items (tableId: 14, total: 58.50)
        {
            orderId: 7,
            menuItemId: 5,
            quantity: 3,
            unitPrice: 12.00,
            subtotal: 36.00,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 10 * 60 * 1000).toISOString(),
        },
        {
            orderId: 7,
            menuItemId: 8,
            quantity: 1,
            unitPrice: 13.00,
            subtotal: 13.00,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 10 * 60 * 1000).toISOString(),
        },
        {
            orderId: 7,
            menuItemId: 10,
            quantity: 1,
            unitPrice: 6.00,
            subtotal: 6.00,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 10 * 60 * 1000).toISOString(),
        },
        {
            orderId: 7,
            menuItemId: 1,
            quantity: 1,
            unitPrice: 3.50,
            subtotal: 3.50,
            notes: null,
            status: 'served',
            createdAt: new Date(threeHoursAgo.getTime() + 10 * 60 * 1000).toISOString(),
        },

        // Order 8 items (tableId: 8, total: 27.50)
        {
            orderId: 8,
            menuItemId: 6,
            quantity: 2,
            unitPrice: 10.00,
            subtotal: 20.00,
            notes: null,
            status: 'served',
            createdAt: new Date(twoHoursAgo.getTime() + 55 * 60 * 1000).toISOString(),
        },
        {
            orderId: 8,
            menuItemId: 9,
            quantity: 1,
            unitPrice: 5.00,
            subtotal: 5.00,
            notes: null,
            status: 'served',
            createdAt: new Date(twoHoursAgo.getTime() + 55 * 60 * 1000).toISOString(),
        },
        {
            orderId: 8,
            menuItemId: 4,
            quantity: 1,
            unitPrice: 2.00,
            subtotal: 2.00,
            notes: null,
            status: 'served',
            createdAt: new Date(twoHoursAgo.getTime() + 55 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(orderItems).values(sampleOrderItems);
    
    console.log('✅ Orders served seeder completed successfully - Created 8 orders with served status ready for payment testing');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});